codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...75"

  status:
    project:
      default:
        threshold: 60
    patch:
      default:
        threshold: 90
